language: go

# Only the last two Go releases are supported by the Go team with security
# updates. Any older versions be considered deprecated. Don't bother testing
# with them.
go:
  - 1.10.x
  - 1.x

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - export GOPATH=`pwd`

script:
  - go build -o fibonacci src/main.go
  - go test src/main.go src/main_test.go -v
  - go test src/fib/fib.go src/fib/fib_test.go -v
  - go test src/fib/fib.go src/fib/fib_test.go -test.bench=".*"

deploy:
